# Generated by Django 4.0.5 on 2022-06-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=120, verbose_name='ru_name')),
                ('en_name', models.CharField(max_length=120, verbose_name='en_name')),
                ('alter_name', models.CharField(max_length=120, verbose_name='alter_name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('volume_number', models.IntegerField(verbose_name='volume_number')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='books.title', verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Volume',
                'verbose_name_plural': 'Volumes',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(verbose_name='chapter_number')),
                ('content', models.TextField(verbose_name='content')),
                ('likes', models.IntegerField(default=0, verbose_name='likes')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.volume', verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('title', 'volume_number'), name='unique volume_number'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('volume', 'chapter_number'), name='unique chapter_number'),
        ),
    ]
